service: StorageApp-Serverless

provider:
  name: aws
  runtime: nodejs20.x
  region: ap-south-1 # CHANGE THIS to your preferred region (e.g., ap-south-1 for Mumbai)
  memorySize: 1024 # High memory for all operations, including CPU-intensive bcrypt
  timeout: 30 # Adjust based on your app's needs
  httpApi:
    cors:
      allowedOrigins:
        - https://cloudvault.cloud
        - https://www.cloudvault.cloud
        # Note: If you have a custom domain in CLIENT_ORIGIN, add it here as well.
      allowedHeaders:
        - Content-Type
        - Authorization
        - set-cookie
      allowedMethods:
        - '*'
      allowCredentials: true
      maxAge: 600 # 10 minutes cache for preflight

functions:
  api:
    handler: lamda.handler
    events:
      - httpApi: '*' # This makes it a catch-all for all routes

package:
  # This ensures we only upload what's necessary to keep the package small
  patterns:
    - "!**"
    - "app.js"
    - "lamda.js"
    - "package.json"
    - "config/**"
    - "controllers/**"
    - "middlewares/**"
    - "models/**"
    - "routes/**"
    - "services/**"
    - "utils/**"
    - "validators/**"
    - "node_modules/**"
    - "package-lock.json"
    - "!.git/**"
    - "!.env" # Excluded because you will add variables manually
    - "!test/**"
    - "!StorageApp-Serverless/**"