name: Deploy Backend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: SSH and Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            set -e
            # 1. Update this to your ACTUAL folder name on EC2
            cd /home/ubuntu/Personal-Cloud-Drive-Backend-PM2
            
            # 2. Pull the latest code
            git pull origin main
            
            # 3. Install dependencies (inside the server folder)
            cd server
            npm ci
            
            # 4. Restart your app with PM2
            /usr/local/nodejs/bin/pm2 reload StorageApp
            
            # 5. Reload Nginx
            sudo systemctl reload nginx